export { default as About} from "./About"
export { default as Product} from "./Product"
export { default as Home} from "./Home"
export {default as Footer} from "./footer/Footer"
export {default as TitleCard} from "./TitleCard"
